name: anduril

on: [ push, pull_request ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      # allow 'git describe' to work, by fetching tags and history
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Requirements
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qqy install avr-libc binutils-avr gcc-avr unzip wget

    - name: Cache Atmel DFPs
      id: cache-dfp
      uses: actions/cache@v3
      env:
        cache-name: cache-dfp-files
      with:
        path: arch/dfp
        # new cache whenever the dfp-install script changes
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('bin/dfp-install.sh') }}

    - name: Install Atmel DFPs
      if: steps.cache-dfp.outputs.cache-hit != 'true'
      run: |
        ./make dfp

    - name: Compile Some
      run: |
        USER=gretel ./make hw/fireflies/pl47g2/anduril.h
        USER=gretel ./make hw/wurkkos/fc13/anduril.h
        USER=gretel ./make hw/wurkkos/ts10/anduril.h
        USER=gretel ./make hw/wurkkos/ts10/rgbaux/anduril.h
        USER=gretel ./make hw/wurkkos/ts11/anduril.h
        USER=gretel ./make hw/wurkkos/ts21-v2/anduril.h
        USER=gretel ./make hw/wurkkos/ts25/anduril.h
        echo "ARTIFACT_NAME=${GITHUB_WORKFLOW}-$(echo "${GITHUB_REF_NAME}" | tr '":<>|*?\\/' '_')-$(git rev-parse --short ${GITHUB_SHA})-${GITHUB_RUN_NUMBER}" >> "${GITHUB_ENV}"

    - name: Store Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error
        path: |
          hex/*.hex
