name: anduril

on: [ push, pull_request ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Requirements
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qqy install avr-libc binutils-avr gcc-avr unzip wget

    - name: Cache Atmel DFPs
      id: cache-dfp
      uses: actions/cache@master
      env:
        cache-name: cache-dfp-files
      with:
        path: arch/dfp
        # new cache whenever the dfp-install script changes
        key: ${{ runner.os }}-${{ env.cache-name }}-${GITHUB_SHA}

    - name: Install Atmel DFPs
      if: steps.cache-dfp.outputs.cache-hit != 'true'
      run: |
        ./make dfp

    - name: Compile Anduril
      continue-on-error: true
      run: |
        USER=gretel ./make anduril
        echo "ARTIFACT_NAME=${GITHUB_WORKFLOW}-$(echo "${GITHUB_REF_NAME}" | tr '":<>|*?\\/' '_')-$(git rev-parse --short ${GITHUB_SHA})-${GITHUB_RUN_NUMBER}" >> "${GITHUB_ENV}"

    - name: Store Artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error
        path: |
          hex/*.hex
